### ISSUE TITLE
Is there a difference between using alexa-app and alexa-app-server

### ISSUE THREAD

**Issue by quentinfasquel** [artsy/elderfield#60]
Hello there,

I am sorry if this question is silly but I would love a quick answer on that subject.
There seems to be the two following ways of serving an Alexa Skill app over https (instead of a Lambda):

```
var app = express();
var alexaApp = new Alexa.app('myApp');
alexaApp.express({
  expressApp: app,
  ...
});

const httpServer = require('http').createServer(app);
httpServer.listen(8080, ...);
```

and

```
var AlexaAppServer = require('alexa-app-server');
AlexaAppServer.start({
  port: 8080,
  app_dir: "myAlexaAppDir",
  ...
});
```

Thanks.

**Comment by dblock** [comment]
Alexa-app-server can host multiple apps, supports HTTPs and has a development mode simulator. I think SSL is the only major differentiator for production skills with a single function.
